name: FinPulse CI

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev
jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Install ta-lib
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential wget
                wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz 
                tar -xzf ta-lib-0.4.0-src.tar.gz
                cd ta-lib
                ./configure --prefix=/usr
                make 
                sudo make install
                cd ..

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            
            - name: Install Poetry
              run: |
                curl -sSL https://install.python-poetry.ord | python3 -
                echo "$HOME/.local/bin" >> $GITHUB_PATH
            
            - name: Cache Poetry dependencies
              uses: actions/cache@v4
              with:
                path: ~/.cache/pypoetry
                key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
                restore-keys: |
                 ${{ runner.os }}-poetry-
            
            - name: Install dependencies
              run: | 
                poetry install
            
            - name: Run FinPulse
              run: |
                poetry run python -m finpulse.main
            
            - name: Run linting
              run: |
                poetry run pip install flake8
                poetry run flake8 src --max-line-length=120
            
            - name: Run tests
              run: |
                poetry run pip install pytest
                poetry run pytest tests --verbose
            
